name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: PingPong
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '7'
        
          
      - name: Install dependencies
        run: dotnet restore "../PingPong/PingPong.csproj"
      - name: Build
        run: dotnet build "../PingPong/PingPong.csproj"
      - name: Test with the dotnet CLI
        run: dotnet test "../PingPong/PingPong.csproj"
